# Generated by Django 5.0.3 on 2024-04-03 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36)),
                ('link', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='media/projects_photos')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('image', models.ImageField(upload_to='media/skills_photos')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='projects.project')),
            ],
        ),
    ]
